# Generated by Django 5.0.4 on 2024-05-01 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ejercicio',
            new_name='EjercicioCategoria',
        ),
    ]
