# Generated by Django 5.0.4 on 2024-05-23 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clase', '0003_ejerciciocategoria_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejerciciocategoria',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=datetime.datetime.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=datetime.datetime.now, editable=False, null=True),
        ),
    ]
