# Generated by Django 5.0.4 on 2024-05-23 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clase', '0004_alter_ejerciciocategoria_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solucion',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soluciones', to='Clase.ejerciciocategoria'),
        ),
    ]
