# Generated by Django 5.0.4 on 2024-05-23 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clase', '0005_alter_solucion_ejercicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solucion',
            old_name='ejercicio',
            new_name='ejercicio_id',
        ),
    ]
